---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local

  vars_prompt:
    - name: "game_username"
      prompt: "Username"
    - name: "game_password"
      prompt: "Password"

  tasks:
    - name: include project variables
      include_vars:
        file: vars.yml

    - name: copy the conf-file to the new folder hierarchy
      template:
        src: "{{ playbook_dir }}/build/j2/logon_db_addadmin.sql.j2"
        dest: "{{ playbook_dir }}/build/sql/logon_db_addadmin.sql"

    - name: Import logon realmlist
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_login }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/logon_db_addadmin.sql"

    - name: Remove logon_db_addadmin.sql
      file:
        path: "{{ playbook_dir }}/build/sql/logon_db_addadmin.sql"
        state: absent
