---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: include project variables
      include_vars:
        file: vars.yml

    - name: (re-)create the build/sql folder
      file:
        path: "{{ playbook_dir }}/build/sql"
        state: "{{ item }}"
      loop:
        - absent
        - directory

    - name: retrieve the world database
      git:
        repo: "{{ app_repository_db }}"
        dest: "{{ playbook_dir }}/build/sql"
        accept_hostkey: yes

    - name: unzip the world db
      unarchive:
        src: "{{ playbook_dir }}/build/sql/{{ app_repository_db_name }}"
        dest: "{{ playbook_dir }}/build/sql"
        remote_src: yes

    - name: run merge script for sql updates
      shell: ./merge.sh
      args:
        chdir: "{{ playbook_dir }}/build/core/sql/migrations"
    
    - name: copy build sql files to build/sql folder
      copy:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/build/sql"
      with_fileglob:
        - "{{ playbook_dir }}/build/core/sql/*.sql"
        - "{{ playbook_dir }}/build/core/sql/migrations/*_db_updates.sql"

    - name: create the folder hierarchy for mangosd
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ playbook_dir }}/data/mangosd/etc"
        - "{{ playbook_dir }}/data/mangosd/bin"

    - name: copy the binary to the new folder hierarchy
      copy:
        src: "{{ playbook_dir }}/build/server/bin/mangosd"
        dest: "{{ playbook_dir }}/data/mangosd/bin/mangosd"
        mode: u+x,g+x,o+x

    - name: copy the conf-file to the new folder hierarchy
      template:
        src: "{{ playbook_dir }}/build/j2/mangosd.conf.j2"
        dest: "{{ playbook_dir }}/data/mangosd/etc/mangosd.conf"

    - name: create the folder hierarchy for realmd
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ playbook_dir }}/data/realmd/etc"
        - "{{ playbook_dir }}/data/realmd/bin"

    - name: copy the binary to the new folder hierarchy
      copy:
        src: "{{ playbook_dir }}/build/server/bin/realmd"
        dest: "{{ playbook_dir }}/data/realmd/bin/realmd"
        mode: u+x

    - name: copy the conf-file to the new folder hierarchy
      template:
        src: "{{ playbook_dir }}/build/j2/realmd.conf.j2"
        dest: "{{ playbook_dir }}/data/realmd/etc/realmd.conf"

