version: '3.7'

services:
   db:
     container_name: vmangosdocker_db
     image: mangos-db
     volumes:
       - ./data/dbdata:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=mangos

   web:
     depends_on:
       - php
     image: nginx:latest
     volumes:
       - ./data/www:/code
       - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
     networks:
       - default
       - dmz

   php:
     build:
       context: ./docker/php
     depends_on:
       - db
     volumes:
       - ./data/www:/code

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin:latest
     environment:
       - PMA_HOSTS=db
       - PMA_VERBOSES='MangOS MySQL Server'
     ports:
       - "8000:80"
     volumes:
       - /sessions

   realmd:
     depends_on:
       - db
     image: realmd
     ports:
       - "3724:3724"
     restart: always
     volumes:
       - ./data/realmd:/server

   mangosd:
     tty: true
     stdin_open: true
     depends_on:
       - db
       - realmd
     image: mangosd
     volumes:
       - ./data/mangosd:/server
       - ./data/datadir:/server/data
     ports:
       - "8085:8085"
     restart: always

networks:
  default:
  dmz:
    name: dmz
