version: '3'

services:
   db:
     image: lh-db
     ports:
       - "3306:3306"
     volumes:
       - ./data/dbdata:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=mangos

   web:
     depends_on:
      - db
     image: phpmyadmin/phpmyadmin:latest
     environment:
      - PMA_HOSTS=db
      - PMA_VERBOSES='MangOS MySQL Server'
     ports:
      - "8000:80"
     volumes:
      - /sessions

   realmd:
     depends_on:
       - db
     image: lh-realmd
     ports:
       - "3724:3724"
     restart: always
     volumes:
       - ./data/realmd:/server

   mangosd:
     tty: true
     stdin_open: true
     depends_on:
       - db
       - realmd
     image: lh-mangosd
     volumes:
       - ./data/mangosd:/server
       - ./data/datadir:/server/data
     ports:
       - "8085:8085"
     restart: always
