---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: include project variables
      include_vars:
        file: vars.yml
    
    - name: Make sure the update files exist
      file:
        path: "{{ item }}"
        state: touch
      loop:
        - "{{ playbook_dir }}/build/sql/world_db_updates.sql"
        - "{{ playbook_dir }}/build/sql/logon_db_updates.sql"
        - "{{ playbook_dir }}/build/sql/characters_db_updates.sql"
        - "{{ playbook_dir }}/build/sql/logs_db_updates.sql"

    - name: Import world database updates
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_world }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/world_db_updates.sql"

    - name: Import logon database updates
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_login }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/logon_db_updates.sql"

    - name: Import characters database updates
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_characters }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/characters_db_updates.sql"

    - name: Import logs database updates
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_logs }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/logs_db_updates.sql"




