---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: include project variables
      include_vars:
        file: vars.yml

    - name: Import world database
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_world }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/{{ app_repository_db_name }}"

    - name: Import logon database
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_login }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/logon.sql"

    - name: Import characters database
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_characters }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/characters.sql"

    - name: Import logs database
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_logs }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/logs.sql"

    - name: copy the conf-file to the new folder hierarchy
      template:
        src: "{{ playbook_dir }}/build/j2/logon_db_realmlist.sql.j2"
        dest: "{{ playbook_dir }}/build/sql/logon_db_realmlist.sql"

    - name: Import logon realmlist
      mysql_db:
        login_host: "{{ db.address }}"
        login_user: "{{ db.username }}"
        login_password: "{{ db.password }}"
        name: "{{ db.db_login }}"
        state: import
        target: "{{ playbook_dir }}/build/sql/logon_db_realmlist.sql"

