#!/bin/bash

USERNAME_UPPERCASE=${WOW_USERNAME^^}
PASSWORD_UPPERCASE=${WOW_PASSWORD^^}

FILE_SQL_TEMPLATE="db_logon_add_admin.template"

USERNAME_DB=${USERNAME_UPPERCASE}
PASSWORD_DB=$(echo -n "${USERNAME_UPPERCASE}:${PASSWORD_UPPERCASE}" | sha1sum | awk '{print $1}')
SHA_PASS_HASH=${PASSWORD_DB^^}

sed -e "s/VARIABLE_USERNAME/${USERNAME_DB}/" -e "s/VARIABLE_SHA_PASS_HASH/${SHA_PASS_HASH}/" ${FILE_SQL_TEMPLATE}
