---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: start the project
      docker_compose:
        project_src: docker
      register: output

      debug:
        var: output
